### ISSUE TITLE
First Person Body HUGE!!

### ISSUE THREAD

**Issue by Raezroth** [tr7zw/FirstPersonModel#349] opened 2023-04-09 22:20 UTC
While using this mod with Vivecraft, the players body is scaled way too big. 

Is there a way to scale the first person model so it fits??

**Comment by tr7zw** [comment] 2023-04-09 22:47
This mod is not really designed to work with vivecraft. Even if the scale would be right, the body would be in the wrong place and shift around a lot.

**Comment by tr7zw** [comment] 2023-05-30 20:21
Duplicate of #328

**Closed by tr7zw** 2023-05-30 20:21 UTC
