### ISSUE TITLE
Hand blocks spyglass

### ISSUE THREAD

**Issue by Aceplante2** [tr7zw/FirstPersonModel#332] opened 2023-02-05 09:31 UTC
Title. Not sure if it is this mode alone but I also use it with not enough animations, but whenever I use spyglass i have to keep shifting my player becuase the hand constantly blocks the lens

**Comment by tr7zw** [comment] 2023-05-30 20:23
Duplicate of already fixed #222

**Comment by Aceplante2** [comment] 2023-05-30 20:51
forge 1.18.2 by the way

**Comment by tr7zw** [comment] 2023-05-30 20:52
Nep. Still already fixed in 2.2.2. Releasing 2.2.3 rn for 1.18.2, it's still fixed.

**Comment by tr7zw** [comment] 2024-01-17 19:08
The mod turns off while scoping, so should be gone for good.

**Closed by tr7zw** 2024-01-17 19:08 UTC
