### ISSUE TITLE
Sneak camera position won't change

### ISSUE THREAD

**Issue by DarianStardust** [tr7zw/FirstPersonModel#407] opened 2024-01-01 23:28 UTC
I'm trying to adjust the Sneak camera position, but no matter how much I change the slider on the config, it stays centered, which is really bad because I can't see anything under me with the camera position when sneaking

The "Standing Up" slider works in game, I can change it live, Sitting also works if I remember, just not sneak, it just ignores what I change, unless I'm doing something wrong on the configs, but it's beyond what I understand

1.20.1 Neoforge

**Comment by tr7zw** [comment] 2024-01-02 17:41
Then you have some incompatible mod installed.

**Comment by DarianStardust** [comment] 2024-01-02 18:13
> Then you have some incompatible mod installed.

what are the generally incompatible mods with this one? I don't know where to start looking/testing

**Comment by tr7zw** [comment] 2024-01-02 18:15
Afaik this player scale mod causes this exact issue. Dont remember which one exactly.

**Comment by DarianStardust** [comment] 2024-01-02 18:21
> Afaik this player scale mod causes this exact issue. Dont remember which one exactly.

Player "Scale"? I have a mod for size shifting potions + it's library, is that it?

**Comment by tr7zw** [comment] 2024-01-02 18:23
Possible. Mods like Figura/Identity have a few open issues, also "squishy API" which is probably also related.

**Comment by DarianStardust** [comment] 2024-01-03 21:42
> Possible. Mods like Figura/Identity have a few open issues, also "squishy API" which is probably also related.

I have Pehkui, which is a Player Size(and other stuff) library mod, required for playing with Origins mod, and I don't think origins itself causes the issue, I switched to Human and it still happens.
 What do you specifically mean by "Scale"? I think of size, but I might be looking the wrong way

Just to confirm, Sitting camera is fine, It's only sneak camera really

**Comment by tr7zw** [comment] 2024-01-03 21:43
Pehkui, thats the one. And yes, player size.

**Comment by DarianStardust** [comment] 2024-01-07 00:57
> Pehkui, thats the one. And yes, player size.

Well, is there anything I can do, outside of just deleting Pehkui? and, curiosity: is the issue "coming" from Pehkui, or FirstPerson? which one would need to update for compatibility first?

**Comment by tr7zw** [comment] 2024-01-07 00:59
The issue is that both mods do something, probably overwriting each other. So its not really any mods fault, just generally incompatible. Also haven't had the time or interest to look into this.

**Comment by DarianStardust** [comment] 2024-01-07 01:11
> The issue is that both mods do something, probably overwriting each other. So its not really any mods fault, just generally incompatible. Also haven't had the time or interest to look into this.

Understandeable, tho, in regards to interest, due to the issue with the sneak camera I have to nearly always toggle off the mod whenever I build, only using it during fights/Not-Building. it's not a priority perhaps, certainly hurts quality of life. and it would be awesome if those two mods worked together, some time in the future maybe, patience

**Comment by tr7zw** [comment] 2024-01-17 17:03
Fixed in the dev version.

**Closed by tr7zw** 2024-01-17 17:03 UTC

**Comment by DarianStardust** [comment] 2024-01-17 23:24
> Fixed in the dev version.

What's a "Dev Version"? also NICE!

**Comment by tr7zw** [comment] 2024-01-18 13:07
> > Fixed in the dev version.
> 
> What's a "Dev Version"? also NICE!

At the top click on Actions, then the latest build of ``wip/allinone``, then Artifacts at the bottom.
