### ISSUE TITLE
Some setting descriptions are unreadable

### ISSUE THREAD

**Issue by NetflixGutschein** [tr7zw/FirstPersonModel#95] opened 2021-02-20 13:40 UTC
Some descriptions in the settings (using ModMenu) are partly unreadable on bigger gui scales, because the entire text is in one single line
and sometimes just goes to outside the screen. Some line breaks would be nice.

https://i.imgur.com/V5RqTpp.png
https://i.imgur.com/iCgYIWg.png

**Comment by tr7zw** [comment] 2021-02-20 13:42
Duplicate of #64

**Closed by tr7zw** 2021-02-20 13:42 UTC
