### ISSUE TITLE
incompatibility with identity

### ISSUE THREAD

**Issue by baldi2** [tr7zw/FirstPersonModel#391] opened 2023-10-30 06:21 UTC

**Comment by baldi2** [comment] 2023-10-30 06:22
it crashes on start

**Comment by tr7zw** [comment] 2024-01-17 17:20
Correct, both mods modify the shadow offset. Not fixable without the cooperation of Identity.

**Comment by tr7zw** [comment] 2024-01-17 17:57
Also duplicate of #353

**Closed by tr7zw** 2024-01-17 17:57 UTC
Labels: other mod
