### ISSUE TITLE
(1.12.2) Backport & Support Mods

### ISSUE THREAD

**Issue by BoraiperXD** [tr7zw/FirstPersonModel#313] opened 2022-11-22 13:35 UTC
I understand that Real First Person 2 has been abandoned & is no longer supported, so I requested that you backport 1.12.2, please, and for the love of god make compatibility w/ Aqua Acrobatics & the Mo' Bends, which are godlike mods for an incredible combination, better quality, and much fun in a modpack, but also since u made modern client mods and improved deep into the legacy version, such as wavey capes & 3D skin layers too. Ty, I hope you've seen my post and this is my only request here.

**Comment by tr7zw** [comment] 2022-11-22 15:21
Like I've listed on https://tr7zw.github.io/versions/ and stated a few times on Discord, currently, I have no real interest in porting any more mods to 1.8/1.12(only adding the missing entityculling 1.12 port). Added to that, "Real First Person 2" is already a thing. 
> Real First Person 2 has been abandoned & is no longer supported

And so are my 1.8/1.12 versions of 3d Skin Layers and WaveyCapes. They are equally not actively supported.

BUT, I just remembered that I do have working 1.12 Forge mod source that does include ``Real First-Person Render 8.1.1``(https://www.curseforge.com/minecraft/mc-mods/real-first-person-render/files/2378343), and according to the sites license, I could publish it. But on the other hand, what would be the point? It's 1:1 the same mod. And last time I tested it, it also did work with Mo'Bends(sometime in 2017/18).

**Comment by BoraiperXD** [comment] 2022-11-23 13:08
How about aquatic acrobatics? I tried to test them yesterday in my modpack, and then I loaded a world, though it didn't maintain a proper view & only shows the inside of a player's head while swimming in the water with RFP 2/first-person render mod. Sorry, I didn't have screenshots to show yet and forgot. (I'll be back later or tom.)

**Comment by BoraiperXD** [comment] 2022-11-23 13:11
Also with crawling..

**Comment by tr7zw** [comment] 2022-11-23 14:56
I'll be quite honest: thats the issues you have with using a legacy version. Update to 1.19 and the issues are gone^^. I really don't get why people forcefully try to stay on these old broken mc versions.

**Comment by BoraiperXD** [comment] 2022-11-24 06:15
Tbh, I'm not a fan of the latest versions of mods, but I really don't hate them, and they're such good mods like Create, Alex's Mobs, and even Sodium, which has the best performance and makes the frame rate increase laggier than vanilla (only in fabric), but however, the most annoying issue is to keep updating, fixing bugs, and creating mods over and over again to the latest version, which keeps you waiting for when it will be released, depending on whether it's forge or fabric. While 1.12.2 has 500 more mods than the most recent version. For some reason, it takes too long to code differently, and the modders decided to quit modding because Mojang changed the codes in 1.13.2, so the community, developer crew, or owner wanted to help, stay, and continue working in 1.12.2 forge, which includes The Aether, Scapes, and Run: Parasites, FutureMC, and Emoticons, which are amazing mods, and anything you want to download hundreds of mods, as well as the best modpacks in the minecraft community, such as RLCraft and Pokemons.

**Comment by tr7zw** [comment] 2022-11-25 23:09
The people didn't stop modding with 1.13. The entire root cause of this issue is Forge. Forge(especially in the 1.12 times) is fragile as hell. Each update took a lot of time for the devs(Forge and mods). And with the 1.13 changes, Forge took I think nearly a year or till 1.14 to update. And then all the mod devs needed to update, which again took ages. Meanwhile in 1.14 Fabric was born, which makes updating really easy for us devs. This is the exact reason, why Fabric devs stay basically on the newest possible mc version, while Forge users/mods are always hanging behind still on 1.18, 1.16, 1.12. The solution to this is not to beg devs to redo the entire mod for 1.12.2, but to get people off Forge and on the latest mc version again. The only reason that 1.12 has so many mods, is because of Forges 1.13 issues, and because it's old(so more time to create mods for it). Not because 1.12 is a good version, especially for developers(it's hell to try to create things for 1.8/1.12).

**Comment by BoraiperXD** [comment] 2022-11-30 00:54
Eh.. it doesn't seem difficult to make client-side mods in 1.12, not for server-side. I'm just asking myself to request and want a port for your First-Person mod to legacy & then explain why you made them into the 1.12.2/1.8.9 version, and was it people who asked & wanted to backport them or was it by yourself huh? Even though it doesn't matter when you don't maintain and support your mod currently, it counts as a point here.

**Comment by tr7zw** [comment] 2022-11-30 01:02
I can't quite follow you text. I support my mods, just not for legacy versions. The 1.8/1.12 ports that I have made were due to demand, no alternative being available and to give it a try(to see how hard it is and if people actually download it). And the answers are: there's not much demand for this mod in these versions, there already is an alternative and it's a horrible job to develop for these versions. There is just no reason to spend 10+ hours to reinvent the same mod for a handful of people, especially with it already being a thing.

**Comment by BoraiperXD** [comment] 2022-11-30 03:22
I understood u did well, & I am really sorry for having complained and been negative too much about my thoughts & issues earlier because my only wish is to have created an alternative mod or revived the First-Person/RFP2 for 1.12.2 mod. Well, that's it for my last message.

**Comment by tr7zw** [comment] 2022-11-30 13:22
According to the RFP2 description, it's licensed under MIT. So if you find any dev that cares about 1.12, you can ask them to update/change that mod with whatever you need.

**Comment by strubium** [comment] 2023-04-10 15:07
> I'll be quite honest: thats the issues you have with using a legacy version. Update to 1.19 and the issues are gone^^. I really don't get why people forcefully try to stay on these old broken mc versions.

The cool thing about 1.12.2 is that it's so "old" that mods have been released that let you completely change the game, so modded Minecraft becomes a framework to make into whatever you want. Mods are only good with other mods, with the exception of Create.

> Update to 1.19 and the issues are gone^^

FR!??!!? I know, these issues are fixed because, wow, you fixed them.


Forgive me for being mean, but it bugs me when perfectly viable (for mods at least) versions with big user bases are refused support because "too old, me no like, switch to fabric"

**Comment by tr7zw** [comment] 2023-04-10 15:28
> The cool thing about 1.12.2 is that it's so "old" that mods have been released that let you completely change the game, so modded Minecraft becomes a framework to make into whatever you want. Mods are only good with other mods, with the exception of Create.

The only issue with that logic is, that the entire 1.12.2 Forge tooling just doesn't work anymore in 2023. It doesn't work with modern Java versions, the repositories behind it are long gone, it doesn't work with modern Gradle versions(and the old versions, again not working with modern Java), these Gradle versions and Gradle plugins are entirely unsupported, getting Mixins(which is the modern way to modify the game) running on 1.12/1.8 is just janky and barely works. I did have a somewhat working setup a year ago, which I used to port 3d Skin layers, EntityCulling and WaveyCapes. But I had to redo the entire mod from the ground up, which takes days, for 3d skin layers/waveycapes I had to port large parts of the 1.18 rendering engine to 1.8 because 1.8 is just unable to support it otherwise. In the end, this was a giant amount of work, not many people download them, and they have issues with many unmaintained 5+ year-old mods. Also since then, the entire code setup broke again, so I can't even make new builds/fix bugs. 
And since FirstPerson does have a perfectly working 1.12 version by someone else, why drain many many hours of my limited time into that, instead of making and maintaining my other mods?

> According to the RFP2 description, it's licensed under MIT. So if you find any dev that cares about 1.12, you can ask them to update/change that mod with whatever you need.

This point still stands. People that still play 1.8/1.12 will have to find devs that still use 1.8/1.12. I just prefer using the very latest MC version and supporting the most recent-ish popular versions like 1.18.2 and 1.16.5(as long as it's viable).

> Forgive me for being mean, but it bugs me when perfectly viable (for mods at least) versions with big user bases are refused support because "too old, me no like, switch to fabric"

You are aware that developing mods is a hobby? I do this for fun, not because "that version has a big user base, so I *have* to support it". Working with extremely broken tools and bad mappings is just not fun. Mojang didn't release mappings for 1.12/1.8, and Forge stopped years ago supporting the 1.8/1.12 tools. From a developer's point of view, that version is 100% dead.

**Comment by tr7zw** [comment] 2023-04-10 15:33
If someone can provide me with a setup that runs with Java 17, has Mixin support, working dev mode starting from the command line, best case yarn of even better Mojmap(backported) Mappings, and runs on a modern Gradle version, THEN I could look into it. Afaik only Fabric Legacy currently provides that, but if I release anything for 1.12.2 Fabric, I think some people would be even more unhappy.

**Comment by strubium** [comment] 2023-04-10 20:13
Sorry, i do forget that people have lives sometimes, I didn't mean to disrespect you. 

There's [this](https://gist.github.com/Pokechu22/97bf5bd528eeadef09dcbae8a15b009f) for 1.12.2 MCP mappings but I don't believe it works anymore and I'm sure you're aware of it.

**Comment by tr7zw** [comment] 2023-04-10 20:16
That's for MCP, which is interesting in it's own right, but not helpful for creating 1.12 Forge compatible Mixin mods. I vaguely remember someone having success loading 3d skin layers via lightloader. So maybe it's possible to somehow use Fabric legacy to create the mod, and then boot it on Forge. Something for later, but I'm working in my free time on Exordium for now(and fixing ItemSwapper issues when they come up).

**Comment by tr7zw** [comment] 2023-05-30 22:37
Closing this issue. Due to work and uni I have less time, not more. And still not seeing the point of investing my time into re-inventing the mod for 1.12.2.

**Closed by tr7zw** 2023-05-30 22:37 UTC
