### ISSUE TITLE
Weird behaviour when sitting on "Another Furniture" seating options

### ISSUE THREAD

**Issue by LeonKappaX** [tr7zw/FirstPersonModel#317] opened 2022-12-10 21:05 UTC
Hey! I was trying out some mod combos for a modpack I am working on.
Eventually I tried out Another Furniture and your First-Person Mod.
When sitting down on a chair/bench/sofa/tall stool the body is kinda not in the same position as the players view.
This however only happens when looking from certain angles.
Using AF newest Forge Version and F-P newest Version both for 1.19.2.
I hope I was able show off the issue, english isn't my native language, sorry!
![WEIRD](https://user-images.githubusercontent.com/101868299/206875149-8749afbb-3f86-4b02-908d-4b664a61359d.png)

**Comment by LeonKappaX** [comment] 2022-12-10 21:25
This is also the case for the seat from the create mod

**Comment by tr7zw** [comment] 2022-12-10 21:26
Duplicate of #77

**Closed by tr7zw** 2022-12-10 21:26 UTC
