### ISSUE TITLE
[1.19.2 Forge] Changing the "sneakXOffset" parameter does not work with the "Pehkui" mod 

### ISSUE THREAD

**Issue by Sora-Akuma** [tr7zw/FirstPersonModel#316] opened 2022-12-08 16:35 UTC
The "sneakXOffset" parameter stops working with the "Pehkui" mod. 
Mods: "First-person Model 2.2.0", "Pehkui 3.6.0" and "forge 43.1.57: 1.19.2". 
This is the first time I encountered such a specific problem, so I do not know which of the developers of mods to turn to.

**Comment by tr7zw** [comment] 2022-12-08 16:36
Duplicate of #249

**Closed by tr7zw** 2022-12-08 16:36 UTC
