### ISSUE TITLE
Incompatibility/Suggestion in relation with Freecam Mod

### ISSUE THREAD

**Issue by AzuryxxVortex** [tr7zw/FirstPersonModel#443] opened 2024-04-29 00:18 UTC
Hello! I have a problem where when using [Freecam](https://modrinth.com/mod/freecam), the a default player is blocking any view..
![image](https://github.com/tr7zw/FirstPersonModel/assets/112041895/f1abaa59-2d66-4f7d-bd6f-f6f77c8e0f5f)

which is how Freecam works, but I think something could be done for this.

If Freecam is activated, _never_ render the player model..
This sounds easy to me, but I'm not sure how modding goes.

This is but a simple suggestion, hope it finds you well.
Good day to everyone-

**Comment by AzuryxxVortex** [comment] 2024-04-29 00:46
Oh, I see that it was fixed before, but it's back now in 1.20.1, mod version 2.3.4.

**Comment by MattSturgeon** [comment] 2024-04-29 00:48
Original issue #291, fixed in [this commit](https://github.com/tr7zw/FirstPersonModel/commit/2f5ae9395f770b763f3f5f37a9af88f7a557f3b6) (now regressed).

Current Freecam issue https://github.com/MinecraftFreecam/Freecam/issues/185.

Not sure yet if the issue is with FPM or Freecam, won't be able to investigate for at least a few days either.

**Comment by AzuryxxVortex** [comment] 2024-04-29 01:05
Issue is present on all 1.20.1 versions of FPM and Freecam, 
My guess is that the fix was lost in 1.20+ maybe...

I've tested from FPM 2.2.3 to 2.3.4, and none work correctly alongside Freecam I'm afraid

**Comment by AzuryxxVortex** [comment] 2024-04-29 01:19
I figured it out!
The commit was only for the fabric version of the mod, as the file address stated, and **it was never present in the forge port.**

Thank you @MattSturgeon for pointing out the commit, I wouldn't have found that otherwise.

So, it's fixed for fabric, but not forge.

**Comment by MattSturgeon** [comment] 2024-04-29 03:14
I noticed FPM has a [compile-only dependency](https://github.com/tr7zw/FirstPersonModel/blob/1760a72e724d2cf7325c13485e487b699af02dcb/gradle-compose.yml#L20) on Freecam's fabric build. 

That dependency should also work fine for forge/neoforge, so long as you don't reference any non-common classes, such as `FreecamFabric` or `ModMenuIntegration`, **and** you don't need a runtime dependency. You could use the forge version if you prefer though.

Hopefully enabling your existing fix in Forge builds will be fairly simple and resolves the issue. I don't _currently_ have time to do a PR though.

**Comment by AzuryxxVortex** [comment] 2024-05-31 23:51
This still hasn't been fixed sadly, and newer version of this mod entirely bans Sinytra, telling me to switch to forge- 
Cannot however because it still has the compatibility issue..

**Closed** 2024-06-07 09:29 UTC
