### ISSUE TITLE
Support for firearms modules

### ISSUE THREAD

**Issue by sinterde** [tr7zw/FirstPersonModel#465] opened 2024-06-18 09:05 UTC
Whether it is possible to be compatible with modules such as "tacz", hide the arm of the third person and keep the display of the arm of the first person when holding a gun, so as to achieve the purpose of compatibility. (The final effect should be similar to "battlefield2042")

**Comment by tr7zw** [comment] 2024-06-18 09:10
Closing as a duplicate of all the other gun mod issues.
TLDR: I will not invest time trying to make any gun mod better compatible, as there are too many, it takes too much time(especially for something I personally don't care about, if someone else wants to look into it, have fun), in the end, it doesn't work like you would expect it to(weapons not pointing the right way, line of sight not working, weapon blocking the entire view, missing animations), and this is up to the gun mod devs.

**Closed by tr7zw** 2024-06-18 09:10 UTC
