### ISSUE TITLE
[1.16.5 Forge] Crash with server.

### ISSUE THREAD

**Issue by Cixon** [tr7zw/FirstPersonModel#89] opened 2021-02-06 23:16 UTC
**Context:** I loaded into my server and I took damage from a enemy and was kicked out of the server and prompted with a java error regarding FPM mod.

**Log (Line 3167):**
[latest.log](https://github.com/tr7zw/FirstPersonModel/files/5937855/latest.log)

**Comment by tr7zw** [comment] 2021-02-06 23:22
Duplicate of #86, I guess I'll do the hotfix that prevents this from kicking you from the server, but it should be looked into which forge mod causes that packet to be basically corrupted(Since this technically isn't a bug of the FirstPersonMod, but a bug of some Forge Mod).

**Closed by tr7zw** 2021-02-06 23:22 UTC

**Comment by Cixon** [comment] 2021-02-06 23:26
not sure what it is, everything was working fine until I added 3 new mods...

**Comment by Cixon** [comment] 2021-02-06 23:29
> 
> 
> Which mods are that? Since so far I wasn't able to reproduce it to nail down which mod screws up this packet.

I added [Bigbrain](https://www.curseforge.com/minecraft/mc-mods/big-brain), [Snailmail](https://www.curseforge.com/minecraft/mc-mods/snail-mail), and updated a private mod called SimpleDualWielding which is exactly what it sounds, it also changes the cooldown for all items.

I link it as well if you'd like.

**Comment by tr7zw** [comment] 2021-02-06 23:30
Since another person also found this, I guess it's one of the two public mods :D. I'll test it in a few days, currently busy with exams.

**Comment by Cixon** [comment] 2021-02-06 23:33
Sounds like a deal. If you can't figure out the issue from there, add my discord and I'll send u the private mod by GenZVirus.
It's not a paid mod _(against eula anyway.)_, just a mod that he took down from the curseforge due to there already being a similar mod.
