### ISSUE TITLE
Minecraft crashes when using the mod on a server with a lot players

### ISSUE THREAD

**Issue by NetflixGutschein** [tr7zw/FirstPersonModel#158] opened 2021-06-03 19:34 UTC
i noticed the problem a few months ago, but i played with multiple mods, so i didnt knew, which mod exactly was causing the crashes. I tried this mostly on "play.timolia.de" on jumpworld. Almost every time I join there a server with more than 50 players, and i try to look at the spawn (where most players are), the games freezes for a few seconds and then crashes. I know played a few weeks without Firstpersonmodel, and i had no crashes since then. Now i put it back in and it almost instantly crashed while i was trying to connect to the server with again over 50 players on it. 
I dont know if its something, caused by my computer (because it is really slow and shitty), but i have this problem only with the first person model mod. I really like the mod an want to use it, but its for now only possible in singleplayer (or online with very little players) without My minecraft crashing. 

I will attach a crashlog. 

---- Minecraft Crash Report ----
// There are four lights!

Time: 03.06.21 21:21
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.class_1071.method_4654(class_1071.java:122)
	at net.minecraft.class_742.getSkin(class_742.java:1096)
	at net.minecraft.class_742.handler$zlc001$getSkinTexture(class_742.java:1069)
	at net.minecraft.class_742.method_3117(class_742.java)
	at net.minecraft.class_1007.method_4216(class_1007.java:142)
	at net.minecraft.class_1007.method_3931(class_1007.java:42)
	at net.minecraft.class_922.method_24302(class_922.java:226)
	at net.minecraft.class_922.method_4054(class_922.java:178)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:311)
	at net.minecraft.class_761.method_22977(class_761.java:2120)
	at net.minecraft.class_761.method_22710(class_761.java:1742)
	at net.minecraft.class_757.method_3188(class_757.java:1022)
	at net.minecraft.class_757.method_3192(class_757.java:693)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1071.method_4654(class_1071.java:122)
	at net.minecraft.class_742.getSkin(class_742.java:1096)
	at net.minecraft.class_742.handler$zlc001$getSkinTexture(class_742.java:1069)
	at net.minecraft.class_742.method_3117(class_742.java)
	at net.minecraft.class_1007.method_4216(class_1007.java:142)
	at net.minecraft.class_1007.method_3931(class_1007.java:42)
	at net.minecraft.class_922.method_24302(class_922.java:226)
	at net.minecraft.class_922.method_4054(class_922.java:178)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_745)
	Entity ID: 394792
	Entity Name: Tiefergelegter
	Entity's Exact location: 189.88, 39.00, -505.72
	Entity's Block location: World: (189,39,-506), Chunk: (at 13,2,6 in 11,-32; contains blocks 176,0,-512 to 191,255,-497), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@7953a523
	Location: 38.24,5.81,24.98 - World: (38,5,24), Chunk: (at 6,0,8 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 68.90625
	Delta: 0.43999255
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:311)
	at net.minecraft.class_761.method_22977(class_761.java:2120)
	at net.minecraft.class_761.method_22710(class_761.java:1742)
	at net.minecraft.class_757.method_3188(class_757.java:1022)

-- Affected level --
Details:
	All players: 28 total; [class_746['Njetflix'/397506, l='ClientLevel', x=151.67, y=31.75, z=-530.70], class_745['qamelie'/229406, l='ClientLevel', x=163.63, y=47.00, z=-525.25], class_745['Tiefergelegter'/394792, l='ClientLevel', x=189.88, y=39.00, z=-505.72], class_745['Txnke'/140082, l='ClientLevel', x=166.69, y=31.00, z=-527.28], class_745['HolzExpertTUR'/395100, l='ClientLevel', x=174.19, y=33.81, z=-531.28], class_745['Vantarc'/321624, l='ClientLevel', x=171.16, y=37.00, z=-522.31], class_745['Pixel_Jessy'/344456, l='ClientLevel', x=166.69, y=31.00, z=-527.31], class_745['Escolar'/397469, l='ClientLevel', x=158.38, y=35.16, z=-481.97], class_745['qbeno'/266393, l='ClientLevel', x=164.47, y=47.00, z=-524.94], class_745['XxJulexX2015'/397216, l='ClientLevel', x=166.16, y=31.00, z=-525.78], class_745['Cyber_1j'/301006, l='ClientLevel', x=168.06, y=34.00, z=-518.66], class_745['HotLeOreo'/352465, l='ClientLevel', x=166.69, y=31.00, z=-527.28], class_745['FlawlessCode'/396040, l='ClientLevel', x=176.03, y=35.81, z=-532.00], class_745['LetsPlay2D'/396055, l='ClientLevel', x=126.25, y=29.00, z=-525.19], class_745['MelonCop'/397499, l='ClientLevel', x=169.69, y=31.00, z=-527.69], class_745['taQonicum'/397346, l='ClientLevel', x=165.19, y=31.50, z=-530.69], class_745['HicXD'/395073, l='ClientLevel', x=148.34, y=33.68, z=-526.28], class_745['inFamousName'/396609, l='ClientLevel', x=155.06, y=35.00, z=-520.66], class_745['Herzensfreundin'/396109, l='ClientLevel', x=162.00, y=33.00, z=-538.97], class_745['DevMoritz'/271977, l='ClientLevel', x=196.41, y=71.00, z=-482.47], class_745['Janettangelina'/394896, l='ClientLevel', x=159.56, y=33.50, z=-540.91], class_745['jn_Zombie'/397212, l='ClientLevel', x=163.50, y=32.00, z=-528.50], class_745['_Klatschy_'/397465, l='ClientLevel', x=165.59, y=48.00, z=-563.72], class_745['physanus'/394932, l='ClientLevel', x=159.00, y=33.50, z=-540.56], class_745['_Tetzel_'/397019, l='ClientLevel', x=160.69, y=33.14, z=-531.81], class_745['J4mPr0'/394721, l='ClientLevel', x=142.31, y=31.50, z=-525.59], class_745['satns'/322804, l='ClientLevel', x=163.50, y=32.00, z=-528.50], class_745['Feuerwelle'/186677, l='ClientLevel', x=174.94, y=36.00, z=-466.25]]
	Chunk stats: Client Chunk Cache: 18225, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (170,4,-520), Chunk: (at 10,0,8 in 10,-33; contains blocks 160,0,-528 to 175,255,-513), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 7380658 game time, 697000 day time
	Server brand: iTz_xXBungeeCordXxHD_PVP (git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:8fde32f:unknown) <- TPapier(2a55fac)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 926119736 bytes (883 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.2
		betterbiomeblend: Better Biome Blend 1.16.4-1.1.3-fabric
		betterthirdperson: Better Third Person 1.3.0
		blur: Blur (Fabric) 2.1.0
		borderlessmining: Borderless Mining 1.0.6+1.16.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.19
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		darkness: True Darkness 1.6.58
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		dynmus: Dynamic Music 1.1.0
		entityculling: EntityCulling-Fabric 1.2.2
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-start-the-music: Start the Music! 0.2.1
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.0.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		llamasteeds: Llama Steeds 2020.2.8
		mermod: Mermod 1.4
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 1.16.7
		nocreativedrift: NoCreativeDrift 1.16.5-1.0.2.0-fabric
		notenoughanimations: NotEnoughAnimations 1.2.4
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		optifabric: OptiFabric 1.9.6
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		satin: Satin 1.5.1
		transliterationlib: TRansliterationLib 1.0.4
		vertical_hotbar: Vertical Hotbar 0.1.1+1.16.2
		voidfog: Void Fog 2.4+1.16.2
		wildfire_gender: Wildfire's Female Gender Mod 2.5.3
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce 940MX/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Iron+Golem+Ricardo+Milos+Edition (incompatible), file/Njetflix's own resourcepack, Fabric Mods
	Current Language: English (United Kingdom)
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce 940MX/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G8
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\******\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G8\Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by tr7zw** [comment] 2021-06-08 15:38
Hm I've looked into it, but I can't seem to find any direct connection. Might have been some conflict between two mods or so.

**Comment by Hackelsepp** [comment] 2021-07-10 06:28
It seems the crash caused by is own Player.... or client xD also i read different Player names that can also the cause...
I have also a issue with First Person render with Ice and Fire : Dragons.... crash log here : https://pastebin.com/pgegJR80
I don't Know how it react with dragons or so i had also a crash caused by a dumb Spruce Sapling don't Know how it happen here also the Crash Log : https://pastebin.com/LCTVN2us

And also so strange its every time a different item or mob thats cause a crash don't Know why...

**Comment by tr7zw** [comment] 2021-08-23 09:54
Going to close this issue because its from 1.16.5 and nothing new did show up while probably being unrelated.

**Closed by tr7zw** 2021-08-23 09:54 UTC
