### ISSUE TITLE
armour trims 

### ISSUE THREAD

**Issue by jonastoverud** [tr7zw/FirstPersonModel#375] opened 2023-08-21 11:58 UTC
hey, when I put an armor trim on my helmet the trim shows op in my face and takes up most of my field of view unless looking completely straight. is there a way to fix this on my side or do I need  to wait till you've updated it.
![Minecraft Forge_ 1 20 1 - Singleplayer 8_21_2023 1_57_30 PM](https://github.com/tr7zw/FirstPersonModel/assets/142801260/46601534-06f7-4a7a-8b60-5cac293df985)

**Comment by tr7zw** [comment] 2023-08-21 12:00
Duplicate of #362

**Closed by tr7zw** 2023-08-21 12:00 UTC
